name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |-
          Hello ${{ github.actor }},

          Thank you for being part of the Anchore community!

          An Anchorite will look at your issue soon. We also have great [documentation](https://docs.anchore.com/current/), including [FAQs](https://docs.anchore.com/current/docs/faq/) and [release notes](https://docs.anchore.com/current/docs/releasenotes/). You can talk to us directly in the [Anchore Community Slack](anchorecommunity.slack.com).

          You can also find our [contribution guidelines here](https://github.com/anchore/anchore-charts/blob/master/CONTRIBUTING.rst). Thank you again!
        pr-message: |-
          Hello ${{ github.actor }},

          Thank you for being part of the Anchore community!

          An Anchorite will look at your PR soon. We value your contribution.

          Please review our [contribution guidelines here](https://github.com/anchore/anchore-charts/blob/master/CONTRIBUTING.rst). You can talk to us directly in the [Anchore Community Slack](anchorecommunity.slack.com). Thank you again!
